### PR TITLE
dear kreg 

### PR DESCRIPTION
**Pull request by Poppy-joe**
uhhh its not the perfect best translation but it works
i couldn't really find ghe suitable words for "hover" but it works ig
i also hope theres no spelling mistakes cuz uhhhh that would be bad
also the fucking word gray out i couldn't understand what it means at all so i just left it there in english, not even google translation could get it

in other words its ehhh but auhhhhh too
that's about it cya

IMG_20240118_233344
IMG_20240118_233448

### CODE REVIEW

**Comment by SpeckyYT** [comment]
> `[Poppygh]`

this isn't valid json

**Comment by Poppy-joe** [comment]
😱😱😱😱😱

**Comment by kr8gz** [comment]
this guy is ysing github for the firs time kmao

**Comment by 3pm-on-github** [comment]
imagine 💀💀

**Comment by SpeckyYT** [comment]
make sure to also update the credits.json file

**Comment by kr8gz** [comment]
he doesnt want a link

**Comment by Poppy-joe** [comment]
noble cause :emoji_61:

**Pull request merged**
